#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : LearningToDS  # The title of the book. Will be placed in the left navbar.
author                      : DistilledData  # The author of the book
copyright                   : "2020"  # Copyright year to be placed in the footer
#logo                        : logo.png  # A path to the book logo

only_build_toc_files: true

# Information about where the book exists on the web
repository:
  url                              : https://github.com/distilleddata/LearningToDS
  path_to_book                     : notebooks
  branch                           : main
  binder_repo_branch               : "main"  # The branch on which your textbook is hosted.
# Binder link settings
  use_binder_button                : true  # If 'true', add a binder button for interactive links  
# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url                    : https://mybinder.org
  colab_url                        : "https://colab.research.google.com"
  thebe                            : true
html:
  use_repository_button            : true
  use_issues_button                : true
